<?php
// AddShoppers Social Shopper Login

// TODO: Set your AddShoppers "API Secret" below (found in https://www.addshoppers.com/merchants under Settings -> API)
$AddShoppersSecret = "";

/*
*
*
* Just adding space between the one line that you need to edit (above) and the rest of the code 
* 
* Trying to make it look nicer :)
*
*
*/


// validate signature 
$params = json_decode($_GET["data"]);
$signature = null;
$p = array();
 
foreach($params as $key => $value)
{
    if($key == "signature")
        $signature = $value;
    else
    	$p[] = $key . "=" . $value;
}
asort($p);
$query = $AddShoppersSecret . implode($p);
$hashed = hash("md5", $query);
if($signature !== $hashed)
        die("Invalid AddShoppers key or bad signature request.");
        
// signature validated, this is a valid request... continue on

//-----get info from url
$urluser = $_GET["asusrnm"];
$urlemail = $_GET["aseml"];

//-----check if	a name and email exist
if(!$urluser){
        //die();
}
if(!$urlemail){
        //die();
}

//-----split name into first name and last name
$arr = explode('_',trim($urluser));
$firstname = $arr[0];
$lastname = array_shift($arr);
$lastname = implode(" ", $arr);

$email = $urlemail;

//-----begin magento create account stuff
error_reporting(E_ALL | E_STRICT);
$mageFilename = 'app/Mage.php';

if (!file_exists($mageFilename)) {
    if (is_dir('downloader')) {
        header("Location: downloader");
    } else {
        echo $mageFilename." was not found";
    }
    exit;
}
require_once $mageFilename;
Varien_Profiler::enable();
//Mage::setIsDeveloperMode(true);
//ini_set('display_errors', 1);
umask(0);


Mage::app('default');

//$session = Mage::getSingleton('customer/session');
//$loginstatus = $session->isLoggedIn();
//$refresh = $loginstatus;


//-----check if user is already logged in, if so stop
Mage::getSingleton('core/session', array('name' => 'frontend'));
$sesscheck = Mage::getSingleton('customer/session', array('name'=>'frontend'));

if($sesscheck->isLoggedIn()){   
	//echo "in";
	die();
}



$customer_email = $email;  	// email adress that will pass by the questionaire 
$customer_fname = $firstname;   // first name from api 
$customer_lname = $lastname;    // last name from api 
$passwordLength = 10;           // the lenght of autogenerated password


$customer = Mage::getModel('customer/customer');
$customer->setWebsiteId(Mage::app()->getWebsite()->getId());
$customer->loadByEmail($customer_email);

$newcust = false;
/*
* Check if the email exist on the system.
* If YES,  it will not create a user account. 
*/


if(!$customer->getId()) {
	//setting data such as email, firstname, lastname, and password 		
  	$customer->setEmail($customer_email); 
  	$customer->setFirstname($customer_fname);
  	$customer->setLastname($customer_lname);
  	$pass = $customer->generatePassword($passwordLength);
  	//$customer->setPassword($customer->generatePassword($passwordLength));
  	$customer->setPassword($pass);

	try{
  	//the save the data and send the new account email.    
  		$customer->save();
  		$customer->setConfirmation(null);
  		$customer->save(); 
  		$customer->sendNewAccountEmail();
	}
	catch(Exception $ex){
 		
	}

	//-----call function to login the users browser session
	$refresh = customerLogin($customer,$email,$pass);
	//customerLogin($customer,$email,$pass);
}
else {
	// login customer here
	// this is secure because we validated the Social Login call using the signature and secret key
	$refresh = customerLogin($customer,$email);
	//customerLogin($customer,$email);
}
cleanIndex($customer->getId());

function customerLogin($customer,$email,$password = ''){

        Mage::getSingleton('core/session', array('name'=>'frontend'));
        $customer = Mage::getModel('customer/customer');
        $customer->setWebsiteId(Mage::app()->getWebsite()->getId());
        $customer->loadByEmail($email);
        
        $session = Mage::getSingleton('customer/session');

        if (!empty($password)) $session->login($email,$password);
        $session->setCustomerAsLoggedIn($customer);
/*
	Mage::getSingleton('core/session', array('name'=>'frontend'));		
	$session = Mage::getSingleton('customer/session');

	if (!empty($password)) $session->login($email,$password);
	else if ($customer->getId()) $session->loginById($customer->getId());
	else return FALSE;
	$session->setCustomerAsLoggedIn($customer);	
	return TRUE;
*/
}

function cleanIndex($custID){
 
        $xml = simplexml_load_file('./app/etc/local.xml', NULL, LIBXML_NOCDATA);
        
        $db['host'] = $xml->global->resources->default_setup->connection->host;
        $db['name'] = $xml->global->resources->default_setup->connection->dbname;
        $db['user'] = $xml->global->resources->default_setup->connection->username;
        $db['pass'] = $xml->global->resources->default_setup->connection->password;
        $db['pref'] = $xml->global->resources->db->table_prefix;

        mysql_connect($db['host'], $db['user'], $db['pass']) or die(mysql_error());
        mysql_select_db($db['name']) or die(mysql_error());

        $qry = 'DELETE FROM ' . $db['pref'] . 'report_viewed_product_index' . ' WHERE customer_id = ' . "'$custID'";
        mysql_query('DELETE FROM ' . $db['pref'] . 'report_viewed_product_index' . ' WHERE customer_id = ' . "'$custID'" ) or die(mysql_error());
            
}




?>

<?php //if($refresh): ?>
<script type="text/javascript">
	window.onload = function refreshParent() 
	{ 
    		window.parent.location.reload(true);
	}
</script>
<?php //endif; ?>
